name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.ded58b9e-6563-4a03-a6dc-54ad95f1a52e }}" | docker login -u "${{ secrets.kusha8 }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.kusha8 }}/static-site .

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.kusha8 }}/static-site
